name: test_flutter
description: "StudyDocs - Quản lý tài liệu học tập"
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ^3.13.2

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    drift: ^2.27.0
    drift_flutter: ^0.2.4
    provider: ^6.1.4
    path: ^1.9.1
    uuid: ^4.5.1
    file_picker: ^13.1.0
    url_launcher: ^6.3.3
    firebase_core: ^4.15.0
    cloud_firestore: ^6.10.0
    firebase_storage: ^13.6.0
    firebase_auth: ^6.7.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
    drift_dev: ^2.27.0
    build_runner: ^2.4.15

flutter:
    uses-material-design: true
