org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# Tắt biên dịch tăng dần (Incremental Compilation) của Kotlin
# để sửa lỗi khác ổ đĩa trên Windows (D:\CODE vs C:\Users\Admin\AppData\Local\Pub\Cache)
kotlin.incremental=false
kotlin.incremental.jvm=false
kotlin.incremental.multiplatform=false
kotlin.incremental.java=false

